### PR TITLE
Submitting a new ACL application to Floodlight

### PR DESCRIPTION
**Pull request by Pengfei-Lu**
Hi! I wonder if I can submit my application to Floodlight as a supplement to the firewall application it contains. Looking forward to your reply, thanks!

Here is the application wiki:

# Introduction
Floodlight contains a firewall application that enforces ACL in a reactive way. In a reactive way, the controller enforces ACL rules by monitoring Packet-in messages and then pushing relevant flow entries, which increases the forwarding delay. Howerver in a proactive way, the controller enforces ACL rules without being requested by the switch, thus to avoid additional delays. The firewall application also has a defect that it can't remove the flow entries that it pushes in time, it means that after removing an ACL rule from Floodlight's storage, the flow entries relevant to that rule still remain in switches and will not expire until after an idle timeout, which can leading to unpredictable network delay or error.

Compared with the firewall application in Floodlight, the ACL application works in a **proactive** way and can manage the ACL flow entries **in time** so as to prevent network error. In more details, the application parses user's RESTful request for ACL updating and enforces that by static flow entries in a proactive way without monitoring Packet-in messages. It can also remove ACL flow entry timely when related ACL rule is removed. 

# REST Interface

## Add a ACL rule:
curl -X POST -d '{"src-ip":"10.0.0.1/32","dst-ip": "10.0.0.2/32","action":"deny" }' http://\<controller_ip\>:8080/wm/acl/rules/json

## Properties of a ACL rule:
Key | Value | Notes
------------ | ------------- | -------------
nw-proto | string | "TCP" or "UDP" or "ICMP" (ignoring case)
src-ip | IPv4 address[/mask] | Either src-ip or dst-ip must be specified.
dst-ip |IPv4 address[/mask] | Either src-ip or dst-ip must be specified.
tp-dst | number | valid when nw-proto == "TCP" or "UDP"
action | string | "DENY" or "ALLOW" (ignoring case), default set to "DENY" if not specified

## Listing ACL rules:
curl http://\<controller_ip\>:8080/wm/acl/rules/json | python -mjson.tool

## Remove a ACL rule:
curl -X DELETE -d '{"ruleid":"1" }' http://\<controller_ip\>:8080/wm/acl/rules/json

## Remove all ACL rules:
curl http://\<controller_ip\>:8080/wm/acl/clear/json

### CODE REVIEW

**Comment by rizard** [comment]
@Pengfei-Lu would you mind doing the following:

(1) pull a new copy of the master branch into your local repo, merging the updates with yours
(2) rename your package to net.floodlightcontroller.accesscontrollist (for clarity) instead of demo.acl
(3) push the changes to your GitHub repo again, which should then automatically update this pull request

I'd like to do an automatic merge, which should be possible after you've incorporated the changes that have been made to master since you originally pulled it down.

Thanks!

**Comment by Pengfei-Lu** [comment]
Hi! @rizard 

I've rename the packet, but I don't know if I pull a new copy of the master branch into my local repo in a right way(I use Synchronize Workspace in Eclipse), is there a better way?

Best,

Alex

**Comment by rizard** [comment]
I've never used that in Eclipse before. I would cd to your local repo.
Then, pull the changes in from Floodlight master, which should do a merge
and show any conflicts that resulted in the merge in your local repo.

Either that, or, you could brute-force make a new clone of the master
branch, copy in your new code to the new Floodlight project, and
force-overwrite your existing fork in your GitHub repo.

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by Pengfei-Lu** [comment]
Hi @rizard !

I think I got it done. I made a new clone of the master branch and added my renamed application code.  Thanks!

Best,
Alex Lu

**Comment by rizard** [comment]
@Pengfei-Lu Okay, it's giving me the option to do an automatic merge, which is good. Thanks for helping me out!

I'll take a look and let you know if there's anything that needs to be modified.

**Comment by rizard** [comment]
@Pengfei-Lu Looks very nice! If you want to make any modifications to the ACL, improvements, etc. in the future, please issue other pull requests to do so.

One other thing --  would you mind writing up some documentation about the ACL such as how to use the REST API, what makes the ACL module different from the existing Firewall module, advantages of the ACL, disadvantages of the ACL, features, limitations, and lastly any bugs and future/ongoing improvement? I'll start a page for you below. You can create an account and fill in all the details. Thanks!

Developer information; things that describe how the module works internally and other items someone who wants to expand the module would want to know (don't talk about how to use the REST API here, but you can link to the other page, below):
https://floodlight.atlassian.net/wiki/pages/viewpage.action?pageId=4882434

Information on how a user would interface with the ACL via the REST API and a brief description of it and what makes it different from the Firewall:
https://floodlight.atlassian.net/wiki/display/floodlightcontroller/ACL+%28Access+Control+List%29+REST+API

Each of the links have similar pages under the same parent with examples of existing documentation. 

Feel free to use parts of your original email or any other materials you already have to write these up.

Thanks again for your contribution!

**Comment by Pengfei-Lu** [comment]
Hi @rizard !

I've added copyright information to my code and finished the wiki page. As a result that English is not my mother tongue, my description may not be appropriate, just let me know what to be improved.

Best Regards,
Alex Lu

**Comment by rizard** [comment]
@Pengfei-Lu

Hi Alex,

Thanks for the quick response and effort! Your English seems near perfect to me and is likely more grammatically correct than mine or most native speakers to be honest =)

I'll take a look though snd merge shortly.

Thanks again for the great contribution! Feel free to contribute other modules you might find useful or fix any that might need improvement -- your help is very much appreciated!

Ryan 

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by Pengfei-Lu** [comment]
Hi @rizard !
I've updated the copyright information. =)

**Comment by rizard** [comment]
Very good! I'll take a look shortly and merge the request. Many thanks for
your contribution!

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by rizard** [comment]
Looks great! Thanks for the contribution and we hope to hear from you again!

**Comment by Pengfei-Lu** [comment]
Thanks a lot! That is really a pleasure of me! =)

**Pull request merged**
