### PR TITLE
HA Support

### PR DESCRIPTION
**Pull request by onebsv1**
The HA Support module:

We have finished running the integration tests, manually, and the unit tests:
https://docs.google.com/document/d/1EJVzzF59_R-jlHwk226_tEjeo6JlWDXfG35Zgz6iYcY/edit?usp=sharing

Here is the module description:
https://docs.google.com/document/d/1cMa2rX_Es8S7X1RFYeV4hRszhnrhxAVjeDxkYFenwbM/edit?usp=sharing

Here is a video explaining how to configure/use this module:
https://www.youtube.com/watch?v=J1AELkF5Yu8

Floodlight-DCO-1.0-Signed-off-by: Bhargav Srinivasan sbhargav3@gatech.edu
Floodlight-DCO-1.0-Signed-off-by: Om Kale omkale@gatech.edu

### CODE REVIEW

**Comment by rizard** [comment]
@onebsv1 sorry for taking so long to get back to you. I figured the review would be more concise in a separate document here:
https://docs.google.com/document/d/1aChKMSvxXCd45Cvw-4WZhxH9mbmr6Z8K0B4sbqF6E7A/edit?usp=sharing

Please feel free to comment either here or in the doc. Overall, your code looks like it does what you intend, but there are some things we need to work through before it can be merged.

**Comment by onebsv1** [comment]
Thank you so much for spending time on the review, it is very detailed and informative! 

We'll work through each of the suggestions, starting with the consolidation of the various Floodlight Module classes into a single Floodlight Module, and using the mentioned socket libraries/sync service to do the communication and replacing ZMQ (which we now understand is a bad idea, sorry for being adamant about it before). We need a bit of time to think about these two issues primarily, and we'll update the doc with comments.

**Comment by onebsv1** [comment]
"java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument" is what is causing the errors coming from the openflow loxigen libs, I'm guessing this maybe because guava is not linked or is not getting loaded, I'm not sure what changed from my end, I'll check.

**Comment by rizard** [comment]
What does your pom.xml look like?

**Comment by onebsv1** [comment]
It needs to be identical to the current pom.xml in the repo, I edited it to remove the jzmq dependency, I'll verify it.

**Comment by rizard** [comment]
We have a patch coming soon. In the meantime, you can edit this from 13.0.1 to 20.0:
https://github.com/floodlight/floodlight/blob/master/pom.xml#L146

**Comment by onebsv1** [comment]
Oh ok, thanks ... I'll try it out tonight

**Comment by rizard** [comment]
@onebsv1 let us know when you're ready for us to take another look

**Comment by omkale** [comment]
Hey Ryan,
We have completely replaced the ZMQServer with a Netty Server and made some other changes to completely remove the ZMQ dependency. You can have a look at it. We will be working on the tutorial sometime this weekend.

**Comment by onebsv1** [comment]
Not yet ... Will need time till the weekend, to implement all the suggestions and also apply the style changes. We will also write a tutorial on how to use the module.

**Comment by omkale** [comment]
Hey Ryan,
The changes you have mentioned have been implemented except replacing primitive type class Integer to int. We have also created a tutorial that can be viewed here:
https://docs.google.com/document/d/1fhm1dOtdYJixCHzfVYOb2iFkRRcyM4Jl2RgrUkVhq64/edit?usp=sharing
Please have a look.

Regards,
Om

**Comment by rizard** [comment]
Thanks @omkale and @onebsv1! We'll take a look

**Comment by onebsv1** [comment]
@rizard Updated the tutorial with a couple of examples (that extend the MACTracker example) which illustrate the use of IHAControllerService and IHAWorkerService, which are provided by this module:

https://docs.google.com/document/d/1fhm1dOtdYJixCHzfVYOb2iFkRRcyM4Jl2RgrUkVhq64/edit?usp=sharing

**Comment by rizard** [comment]
@omkale, @onebsv1 sorry for taking so long on this pull request. Would you mind putting your tutorial in the Google Doc on the wiki as a new page here:
https://floodlight.atlassian.net/wiki/display/floodlightcontroller/Tutorials

Feel free to create an account if you don't have one already. Also, it would be very nice if you could add your module/service here:
https://floodlight.atlassian.net/wiki/display/floodlightcontroller/Floodlight+Services

As well as a brief development writeup here:
https://floodlight.atlassian.net/wiki/display/floodlightcontroller/Controller+Modules

Thanks!

**Comment by onebsv1** [comment]
@rizard Done! We've updated the docs and created a tutorial from the Google Doc, along with a few illustrations.

**Comment by rizard** [comment]
@onebsv1 @omkale sorry for taking so long on this. Are things ready to go now? LGTM

**Comment by omkale** [comment]
No worries. Yes, we have updated the Google doc in the tutorial section, added our module, the services the module provides and a tutorial on the floodlight wiki page as per your last request.
Here are the links to the same:

Tutorial on using the HA Support module:
https://floodlight.atlassian.net/wiki/spaces/floodlightcontroller/pages/82542837/How+to+Sync+Updates+between+Multiple+Controllers+using+High+Availability+Support

Module/service details:
https://floodlight.atlassian.net/wiki/spaces/floodlightcontroller/pages/40402986/Floodlight+Services

Brief development write-up:
https://floodlight.atlassian.net/wiki/spaces/floodlightcontroller/pages/81902392/High+Availability+Support+Dev

Please do let us know your opinion regarding the above.

**Comment by onebsv1** [comment]
Yes, things are good to go now.

**Pull request merged**
