### PR TITLE
IPv6 (New)

### PR DESCRIPTION
**Pull request by phpHavok**
Hi Ryan. I couldn't figure out how to modify my pull request to change branches/commits, so I just closed it and started this new one. This contains everything the last one did except the LoxiGen stuff.

### CODE REVIEW

**Comment by rizard** [comment]
@phpHavok Awesome! =) Thanks for the contribution! Let's follow up on the payloads for ICMPv6 and such eventually. Those would be useful, especially since the OF protocol defines being able to operate on them.

**Comment by phpHavok** [comment]
I agree; ICMPv6 is going to be vital, especially since that's how IPv6 handles "ARP."

**Comment by rizard** [comment]
@phpHavok Yes, let me know if you want to tackle that, otherwise I'll take a look.

**Comment by phpHavok** [comment]
@rizard Sorry it has taken me so long to get back with you. I've been working on a different project/presentation, and I wasn't sure if I was going to be able to work on ICMPv6 or not. As it stands right now, I don't know. I'm going to work on the SPUD class, since it is more readily needed for my project. If you get a chance to look at ICMPv6, go right ahead!

**Comment by rizard** [comment]
@phpHavok No problem! I'll take a look when I can. It'll honestly be at the end of my to-do list right now, since nobody has requested it (but I'll eventually get to it). Thanks again!

**Pull request merged**
