### PR TITLE
Add a callback after an input event has been consumed

### PR DESCRIPTION
**Pull request by paaguti-work**
In addition to the possibility of putting input event handlers in different places of the event handling pipeline, I have encountered a couple of use cases where I really needed to know that an event had been consumed and I couldn't because a module was returning EVENT.STOP.
To cover them, I have included a new handler.

No impact on existing modules. However, I have included the handler in the LearningSwitch to show how it works.

### CODE REVIEW

**Comment by rizard** [comment]
@paaguti-work This is very interesting. Thank you for the contribution! Just curious though -- what use cases do you have where it's necessary to know the end of the packet processing pipeline? Would this also be useful for sending packets from the controller to the switch? We already have a callback for listening to such events, but it also cannot notify at the end of the listening pipeline right before the message is to be written.

I'd like to include this contribution, assuming the unit tests are passing. Unfortunately, there are many conflicts given a recent update to master where I ported the controller to Netty4 and a new version of the OpenFlowJ-Loxi library. Would you mind pulling down those updates, fixing any conflicts, and pushing a commit addressing the conflicts to your master branch?

Lastly, from a design point of view, what are your thoughts on including the functionality of IControllerCompletionListener in IOFMessageListener? It might be more compact to include two registration functions in the IOFMessageListener interface -- one for the normal, ordered packet-processing pipeline and another for pipeline completion. A module could in theory register for both using the single listener interface. The downside to this approach is that I'd have to update the tutorials to reflect the new interface function and more modules that implement this listener will need to be updated. However, if this is cleaner, it'll be worth the effort.

**Comment by paaguti-work** [comment]
Regarding the use cases for this: I'm technical manager of the EU FP-7
project NetIDE and there we are developing a multi-controller network
engine. This engine has a lot of advanced features including an application
composer. We are aiming at composition strategies which go beyond what
CoVisor & co. are offering. For that we need to know when a packet has been
processed by all modules running in a floodlight engine.

Regarding fixing the conflicts, I hope I will be able to do it this week.
Cross fingers with me. I'm really busy (as you see from my delay answering
you) because we are preparing the year 2 review. It would really be nice if
you could help me and we could have this done before the end of February,
so that we could announce this contribution in the review.

Thanks, /PA

**Comment by paaguti-work** [comment]
This was easier than expected! I have made the completionListener in the LearningSwitch a bit less noisy. Where do you want me to document this new callback?

**Comment by paaguti-work** [comment]
BTW, I'd rather keep the completionListener separate. It's not just about tutorials that need to be changed ;-) but because I'd like to keep separate listeners for packet processing and pipeline completion. The events are completely different from a conceptual point of view.

**Comment by rizard** [comment]
@paaguti-work Thanks for the clarification and for updating with master. Assuming the unit tests are passing, I'd be happy to accept this pull request.

Thanks again for the contribution!

**Comment by rizard** [comment]
@paaguti-work Just added Travis-CI (long overdue) to Floodlight. Looks like you have some compile errors.

**Comment by paaguti** [comment]
Fixed compilation problems and made the callback just print a message if enabled in the learning switch class

**Comment by paaguti-work** [comment]
As commented in the pull-request... my flu's fault... sorry :( I have fixed
them now.
mvn test -B gives a couple of errors, but they don't seem related to my
patch. Tell me if I can help.

/PA

**Comment by rizard** [comment]
You'll also want to update these unit tests:

Tests in error:
  testFlood(net.floodlightcontroller.learningswitch.LearningSwitchTest)
  testFlowMod(net.floodlightcontroller.learningswitch.LearningSwitchTest)

testHandleMessagesNoListeners(net.floodlightcontroller.core.internal.ControllerTest)
  testHandleMessages(net.floodlightcontroller.core.internal.ControllerTest)

testHandleMessagesSlave(net.floodlightcontroller.core.internal.ControllerTest)

testHandleMessageWithContext(net.floodlightcontroller.core.internal.ControllerTest)

which are failing with your changes. If you're using Eclipse, it should be
relatively straightforward to see what's wrong with each one given the
stack traces it maintains for each test. It's likely that you need to
implement your new listener in the tests.

Ryan Izard
PhD Candidate, Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by paaguti** [comment]
It took some learning to understand how the tests work. Currently, the fact that the LearningSwitch implements the completion listener helped me to integrate in the current test batch. I hope it is enough.

Best, /PA

**Comment by paaguti** [comment]
Hi, any news on this. I'd like to announce this to the project...

**Comment by rizard** [comment]
@paaguti-work Sorry, I've been tied up in other projects. Looks good to me. I'll merge now. Thanks for the contribution! If you give me your name, I'll update your github handle [at the bottom of this](https://floodlight.atlassian.net/wiki/display/floodlightcontroller/Authors+and+Contributors) accordingly.

**Comment by paaguti-work** [comment]
Hi Ryan,

please include me as
"Pedro A. Aranda Gutiérrez (paaguti) - Telefónica
 I+D on behalf of the NetIDE project (http://www.netide.eu/)"

This is long, I know, but that ack is needed, since the idea came from my
work in this project and the European Union wants publicity for the
projects they co-finance ;-)

Thanks a lot, /PA

**Comment by paaguti-work** [comment]
Hi Ryan, me again... Maybe we could even do some cross-linking between both
pages (like using floodlight / used by NetIDE) :-)

/PA

**Comment by rizard** [comment]
@paaguti-work The page has been updated. Thanks again for your contributions!

**Comment by paaguti** [comment]
Cool !!!
will cross link next week :-)

Thanks, /PA

**Pull request merged**
