### PR TITLE
LinkDiscoveryManager

### PR DESCRIPTION
**Pull request by afranci5**
To handle the Link down events

### CODE REVIEW

**Comment by rizard** [comment]
@afranci5 What did you change here? The diff shows it all as new.

**Comment by afranci5** [comment]
I have added the lines (1479 to 1511).
Please verify.

Thanks & Regards,
Andrew Niteesh

**Comment by rizard** [comment]
Hi Andrew,

I remember this now -- sorry I've been dealing with so much lately that I
forgot about your update.

It looks great except what about non-IPv4 packets?

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by afranci5** [comment]
Hi,

Sorry I didn't get your question.
I am matching the ports which are down on the switches and deleting the
related
flows.

Thanks & Regards,
Andrew Niteesh

**Comment by rizard** [comment]
Hi Andrew,

You are also matching on MatchField.IPv4, which will only allow IPv4 fields
to be removed. What about e.g. ARP or others? If you leave that match out
(remove it), will that work?

Ryan

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by afranci5** [comment]
Oh okay.
But it is working. Could you please verify and let me know, otherwise i
will try to add those also.

Thanks & Regards,
Andrew Niteesh

**Comment by rizard** [comment]
Could you include a unit test that tests for that? You could include a flow
outputting to the port and another listening on the port. Then, check if
they are removed afterwards. Does that make sense?

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by afranci5** [comment]
Yeah sure.. I will update you once it is done

**Comment by rizard** [comment]
@afranci5 Let me know when it's done. I'll take a look then.

**Comment by rizard** [comment]
Hi @afranci5 any updates here?

**Comment by rizard** [comment]
Resolved in https://github.com/floodlight/floodlight/pull/656

**Pull request closed without merging**
