### PR TITLE
Feature/maven integration

### PR DESCRIPTION
**Pull request by oxisto**
I've tried to be as close as possible with the library versions. However, i've bumped the RESTlet versions up to 2.2 to fix some dependecy issues i had with earlier versions because of Jackson dependencies. For netty, i've chosen 3.9.0 over 3.10.0 because the OpenFlowJ artifact already depended on it.

Test are currently (still) disabled

### CODE REVIEW

**Comment by rizard** [comment]
@oxisto This is great! I'm looking into the dependency issues with the unit tests in my spare time. Let me know what you find.

It'll be very useful to have maven and ant as build tools. We can possibly phase out ant once all the maven issues are worked out.

One thing I'll test is SSL compatibility with Netty 3.9.0. Same for RESTlet 2.2. There's no harm in merging this now though.

Thanks!

**Comment by oxisto** [comment]
Actually it is RESTlet 2.3.2, so please go ahead and test the SSL stuff because i only have SSL running on some of the OF switches but not on the REST API in my setup. The dependencies of RESTlet are a bit annoying because they suddenly jumped from jackson 2.1 to 2.4 - in some other projects that i use together with floodlight i have to use jersey which depends on jackson 2.3 but seems to work fine with jackson 2.4. That's why i updated RESTlet again - fingers cross that it works.

I'll also try to look into the unit tests if i have some spare time.

**Comment by oxisto** [comment]
Oh and one more thing: Please let me know if you tag / branch the next minor release so i can edit the pom file accordingly (or i can advise you how to edit it). So on master we currently have the version 1.2-SNAPSHOT. The pom for the next release branch would be 1.2 and after that the master pom should contain 1.3-SNAPSHOT.

**Comment by rizard** [comment]
@oxisto If you're using SSL, have you verified SSL works for your switches? If so, I'll just test RESTlet 2.3.2.

The next minor release will likely be late July or August. I'll let you know when we're getting close.

**Comment by oxisto** [comment]
Not with the recent pom that is now on master, but i can do that.

**Comment by rizard** [comment]
@oxisto It's not a big deal -- I'll test both. While I'm at it, I'll write up some tests to automate this.

**Comment by oxisto** [comment]
It is working with mininet using OVS 2.3.1. However i observe the following (but i'm pretty sure that this was also the case with other netty versions, maybe a general "bug"):

```
2015-06-02 15:01:45.272 INFO  [n.f.c.i.OpenflowPipelineFactory] SSL OpenFlow socket initialized and handler ready for switch.
2015-06-02 15:01:45.379 INFO  [n.f.c.i.OFChannelHandler] New switch connection from /127.0.0.1:65002
2015-06-02 15:01:45.402 INFO  [n.f.c.i.OpenflowPipelineFactory] SSL OpenFlow socket initialized and handler ready for switch.
2015-06-02 15:01:45.405 INFO  [n.f.c.i.OFChannelHandler] New switch connection from /127.0.0.1:65003
2015-06-02 15:01:45.417 INFO  [n.f.c.i.OFChannelHandler] [[? from 127.0.0.1:65002]] Disconnected connection
2015-06-02 15:01:45.755 INFO  [n.f.c.i.OFSwitchHandshakeHandler] Switch OFSwitchBase DPID[00:00:00:00:00:00:00:01] bound to class class net.floodlightcontroller.core.OFSwitch, description SwitchDescription [manufacturerDescription=Nicira, Inc., hardwareDescription=Open vSwitch, softwareDescription=2.3.1, serialNumber=None, datapathDescription=None]
2015-06-02 15:01:45.767 WARN  [n.f.c.i.OFSwitchHandshakeHandler] Switch 00:00:00:00:00:00:00:01 is OF_13 but does not support OFTableFeaturesStats. Assuming all tables can perform any match, action, and instruction in the spec.
2015-06-02 15:01:45.777 INFO  [n.f.c.i.OFSwitchHandshakeHandler] Clearing flow tables of 00:00:00:00:00:00:00:01 on recent transition to MASTER.
2015-06-02 15:01:45.777 WARN  [n.f.c.i.C.s.notification] Switch 00:00:00:00:00:00:00:01 connected.
```

**Comment by rizard** [comment]
Are you referring to the warning about the table features or the connect,
immediate disconnect, and reconnect?

For the warning, OVS does not support table features until 2.3.90. That
version was master a couple weeks ago but has not been released as a minor
version yet. It'll be in the new Floodlight VM I'm working on.

I've seen the double-connect behavior a couple times before, but I'm not
sure what causes it. It looks like the switch is trying to connect twice as
evident from the different TCP ports 65002 and 65003. Maybe that's an
auxiliary connection that happens prematurely?

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by oxisto** [comment]
I was referring to the immediate connect/disconnect, but that seems normal then.

**Comment by rizard** [comment]
Are you observing that happen all the time?

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Pull request merged**
