### PR TITLE
writePacketOutForPacketIn to OFMessageUtils

### PR DESCRIPTION
**Pull request by AndreMantas**
- Created writePacketOutForPacketIn function in OFMessageUtils based on the one from LearningSwitch.
- Modified writePacketOutForPacketIn in LearningSwitch to use the one in OFMessageUtils and still increment the counterPacketOut.
- Ran LearningSwitchTest and both tests passed.

### CODE REVIEW

**Comment by rizard** [comment]
@AndreMantas Makes sense to change LearningSwitch to use the new utility function. Many thanks again!

**Comment by oxisto** [comment]
This pull request is missing an "import net.floodlightcontroller.util.OFMessageUtils;". It does not compile at the moment! (at least not for me :)

**Comment by rizard** [comment]
@oxisto Just reverted in #559. @AndreMantas did you test your code before you issued the pull request?

I'm juggling too many things at once here, so I failed to test it myself :-/

**Comment by AndreMantas** [comment]
Yes i tested in my workspace but i didn't upload the file directly, i edited it in the git page. I completely forgot about the import, but adding that should do it. Sorry for the trouble...

**Comment by rizard** [comment]
@AndreMantas Can you create another pull request with your changes? Or, where did you add the commit?

**Comment by AndreMantas** [comment]
Done. Sorry for the inconvenience. I'm quite new to github. Should have
pushed the file and not edit it directly...

Em ter, 9 de jun de 2015 às 23:49, Ryan Izard <notifications@github.com>
escreveu:

**Comment by rizard** [comment]
@AndreMantas I just merged your change with the imports and reverted my change.

**Comment by AndreMantas** [comment]
@rizard thanks. did you tested it? I hope everything is fine now.

**Comment by rizard** [comment]
@AndreMantas everything works now. Thanks!

**Comment by AndreMantas** [comment]
@rizard glad I could help. Next time I'll use git in a better way, sorry for the inconvenience.

**Pull request merged**
