### PR TITLE
Add support for SPUD

### PR DESCRIPTION
**Pull request by phpHavok**
Hi Ryan,
Here is a changeset that includes the following:

* Add the Jackson CBOR library and update `build.xml` to require it. I did ~~not~~ update `pom.xml` for Maven users.
* Add SPUD BasePacket class. This does not directly make use of the included CBOR library. Instead, I have the CBOR payload being decoded as a `Data` packet which can be manipulated however the user wants (such as taking advantage of the new Jackson CBOR library). This seemed to be the cleanest way to do it.
* Update UDP class to check for SPUD and decode appropriately.
* Add unit tests for SPUD.
* Add unit tests for UDP that check for SPUD.

I will do some more "field testing" on Monday. But for now, at least the coverage is passing.

### CODE REVIEW

**Comment by oxisto** [comment]
Could you add the following diff to your patch to include the library in the maven build as well please?

```
diff --git a/pom.xml b/pom.xml
index a77870f..05c0b17 100644
--- a/pom.xml
+++ b/pom.xml
@@ -219,9 +219,15 @@
                        <artifactId>netty</artifactId>
                        <version>3.9.0.Final</version>
                </dependency>
+               <dependency>
+                       <groupId>com.fasterxml.jackson.dataformat</groupId>
+                       <artifactId>jackson-dataformat-cbor</artifactId>
+                       <version>${lib-jackson-version}</version>
+               </dependency>
        </dependencies>
        <properties>
                <lib-restlet-version>2.3.2</lib-restlet-version>
+               <lib-jackson-version>2.4.4</lib-jackson-version>
                <lib-hamcrest-version>1.3</lib-hamcrest-version>
        </properties>
 </project>
```

Generally, it might be good to consider the appropriate jackson versions. You included 2.5.4 for ant building, whereas the rest of the jackson libraries is 2.1.X. For the maven build, jackson 2.4.4 is used because of dependencies to restlet 2.3.2, so i suggest using 2.4.4 of the CBOR library as well (as specified in this diff).

Maybe it has come the time to generally upgrade the jackson and restlet versions in the ant build as well - 2.1 is quite old.

**Comment by phpHavok** [comment]
@oxisto Does it have to be 2.4.4 or will 2.4.7 work?

**Comment by oxisto** [comment]
@phpHavok I set the version to 2.4.4 because 2.3.2 uses that specific version. Do you need a specific feature of 2.4.7.?

**Comment by phpHavok** [comment]
@oxisto Nah, that's just the default build when pulling from the 2.4 tree. I have to do a manual build for ant. Should I just do a maven build and copy the jar it builds?

**Comment by phpHavok** [comment]
@oxisto Looks like that works. I ran a maven build for Floodlight with the added dependency and copied the jar file for ant from `~/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.4.4`. I'll push the changes shortly.

**Comment by phpHavok** [comment]
There were indeed issues with using CBOR 2.4.4 with other Jackson 2.1.4 libraries. This latest commit upgrades all 2.1.4 libraries to 2.4.4 for ant builds (maven builds are fine since they already reference all 2.4.4 libraries as added in oxisto's patch). I'll report back shortly after some testing to see if this clears things up.

**Comment by phpHavok** [comment]
Awesome, everything is working! I think this is ready for merge if there are no objections.

**Comment by rizard** [comment]
@phpHavok Sorry for getting to this so late! I've been doing a lot of traveling the past couple weeks.

I'm taking a look now and will let you know what I think. I'll operate under the assumption @oxisto has approved the maven integration.

**Comment by rizard** [comment]
@phpHavok This looks great!

**Comment by phpHavok** [comment]
@rizard Thanks, Ryan :) It's no problem at all. Maven is something I haven't tested, but everything is working great for ant. I've had a module doing some SPUD stuff for the past week or so. I haven't had any problems out of it.

**Comment by rizard** [comment]
@phpHavok If it's the latest draft then that is fine. We can always update the code as SPUD does.

Thanks!

**Pull request merged**
