### PR TITLE
add tcp_flags matching to forwarding module

### PR DESCRIPTION
**Pull request by allewwaly**
match only on ovs>=2.1.0 when tcp_flags in introduced.

### CODE REVIEW

**Comment by rizard** [comment]
@allewwaly please the unit test failures for both your pull requests. We also need to wait on your PR https://github.com/floodlight/loxigen/pull/512 to be merged.

**Comment by allewwaly** [comment]
I don't know why there is checking error. It builds and works ok on my machine. (just run ant and java -jar target/floodlight.jar under root directory)

**Comment by rizard** [comment]
@allewwaly where specifically did you reference the TCP flag definitions for this OXM? You've obviously tested them working with your use case, but I'd like to cross reference them to be certain.

**Comment by allewwaly** [comment]
From http://openvswitch.org/support/dist-docs/ovs-ofctl.8.txt
in the  tcp_flags options:

> tcp_flags=[+flag...][-flag...]
>               Bitwise  match on TCP flags.  The flags and mask are 16-bit num‐
>               bers written in decimal or in hexadecimal prefixed by 0x.   Each
>               1-bit  in mask requires that the corresponding bit in flags must
>               match.  Each 0-bit in mask causes the corresponding  bit  to  be
>               ignored.
> 
>               Alternatively,  the  flags  can  be  specified by their symbolic
>               names (listed below), each preceded by either + for a flag  that
>               must  be  set,  or  - for a flag that must be unset, without any
>               other delimiters between the flags.   Flags  not  mentioned  are
>               wildcarded.   For  example,  tcp,tcp_flags=+syn-ack  matches TCP
>               SYNs that are not ACKs.
> 
>               TCP protocol currently defines 9 flag  bits,  and  additional  3
>               bits  are  reserved (must be transmitted as zero), see RFCs 793,
>               3168, and 3540.  The flag bits are,  numbering  from  the  least
>               significant bit:
> 
>               0: fin No more data from sender.
> 
>               1: syn Synchronize sequence numbers.
> 
>               2: rst Reset the connection.
> 
>               3: psh Push function.
> 
>               4: ack Acknowledgement field significant.
> 
>               5: urg Urgent pointer field significant.
> 
>               6: ece ECN Echo.
> 
>               7: cwr Congestion Windows Reduced.
> 
>               8: ns  Nonce Sum.
> 
>               9-11:  Reserved.
> 
>               12-15: Not matchable, must be zero.

**Comment by allewwaly** [comment]
Is there anybody to check this pull request?  As the PR floodlight/loxigen#512 is already merged.

**Comment by rizard** [comment]
@allewwaly Not sure why the build failed (says no symbol MatchFields.OVS_TCP_FLAGS...). Might have been done before the loxi pull request was merged. I'm rerunning it now

**Comment by rizard** [comment]
@allewwaly looks suspicious: https://travis-ci.org/floodlight/floodlight/builds/155709121#L1185

**Comment by rizard** [comment]
@allewwaly the issue is that codehaus, who was hosting our openflowj jar is no longer hosting it. Thus, maven is broken

**Comment by allewwaly** [comment]
@rizard I've updated the openflowj jar with that of  PR [floodlight/loxigen#512](https://github.com/floodlight/loxigen/pull/512)

**Comment by allewwaly** [comment]
@rizard anything need to check or improve?

**Comment by rizard** [comment]
@allewwaly sorry for taking such a long time with this. Looks great now, thanks!

**Pull request merged**
