### PR TITLE
Load Balance Features Updated - #753 Follow-up

### PR DESCRIPTION
**Pull request by OCoutinho**
New Features and  API Documentation can be found: [here](https://github.com/OCoutinho/floodlight/wiki/Load-Balancer-API).

### CODE REVIEW

**Comment by QingWang0909** [comment]
@OCoutinho I put the review in a separate document here: https://docs.google.com/document/d/1gUGeTopZx_7pe0gemzgsUt2iOJQwLvRC4PxpD8lX3JY/edit?usp=sharing

Please feel free to comment in the doc. Overall I think the code structure looks good, but when I try to use REST APIs I got some issues.  Not sure if this is because I mis-use the APIs or what, but we need to work through those issues before we make a merge.

Thanks again for the contribution!

**Comment by OCoutinho** [comment]
@QingWang0909  I will check the issues referred in the doc, I will also update the documentation with request  examples. I'll let you know when I got the issues corrected and ready to merge.

**Comment by rizard** [comment]
@OCoutinho any updates here? Let us know if you are ready for another review

**Comment by QingWang0909** [comment]
@rizard Ryan, @OCoutinho and me actually keep in touch, and we're actually close on finish reviewing this one -- since I am occupied on working with BMF so I can't find time to finish testing it. Let me try to finish it tomorrow and post the update here. 

@OCoutinho I was quite busy on last few months, sorry for taking long for reviewing!

**Comment by qingwang-bsn** [comment]
I think it is ready to go. @OCoutinho thanks again for your great contribution! Do you have anything else to bring on before merging this PR? Please let us know. Otherwise, we can go ahead to merge it now.

**Comment by OCoutinho** [comment]
No problem! All changes are in this PR, I think it is good to go :)

**Comment by QingWang0909** [comment]
@OCoutinho Just merged : ) Thanks again for your kind contribution!

**Pull request merged**
