### PR TITLE
Firewall Optimization

### PR DESCRIPTION
**Pull request by khayatkd**
I don't think the firewall module is receiving rules in the right way for example the current FirewallRulesResource file is accepting this scenario; 

Rule id: 918326031	, Switch: 00:00:00:00:00:00:00:01, Priority: 0, Action: ALLOW
Rule id: 1319725127	, Switch: 00:00:00:00:00:00:00:01, in port: 1, Priority: 0, Action: DENY

With this 2 rules we are accepting and denying the same traffic that comes from port 1 from switch  00:00:00:00:00:00:00:01. 

In my opinion this is not correct because there is an overlapping issue. 
Rule 918326031 is overlapping Rule id 1319725127. 
We shouldn't accept overlaping rules with the same priority because we can be both accepting and denying the same traffic. It is not clear for the user of this firewall witch rule is match and witch rule is not matched. 

If we reject rules this kind of scenarios we can force the user to use different prioritys and avoid overlapping in rules with the same priority. Rules that Overlap other rules should have lower priority ( higher priority value number).

### CODE REVIEW

**Comment by rizard** [comment]
It there a reason you deleted FirewallResourceBase.java? There are some build errors too

**Comment by khayatkd** [comment]
there is no reason... i've made a mistake by deleting that file... i've re uploaded it.

**Comment by khayatkd** [comment]
@rizard All checks have passed. No errors detected.

**Comment by rizard** [comment]
@khayatkd this looks much better. I presume you've run some tests to verify it works? It would be great to have a unit test to verify the overlap is detected and the conflicting rule is discarded, but I understand if you don't have the time

**Comment by khayatkd** [comment]
As soon as i have the time i'll build a bash script with curl post commands so you can check overlap cenarios working correctly.

**Comment by rizard** [comment]
@khayatkd it looks good to me otherwise. I was thinking more of a unit test rather than a bash script. I'll go ahead and merge it. Thanks!

**Pull request merged**
