### PR TITLE
Added weighted RR and switch statistics algorithms for picking members

### PR DESCRIPTION
**Pull request by OCoutinho**
Implemented a function to map the memberId to the port connected to the member and get the corresponding bandwidth.
Using port statistics from StatisticsCollector.java, it is now possible to pick a member based on the received bandwidth of the members associated port.

Added weights to the LBMember class, defaulted to 1.
Added two more REST API methods related to these weights:
- One will change the weight of a given member;
- Other will give priority to a given member by increasing the weight to a value - which takes into account the number of members of that pool. 

Added tests to determined the correctness of these functionalities.

### CODE REVIEW

**Comment by rizard** [comment]
@OCoutinho this is very nice! Thank you for including tests!

**Comment by omidit** [comment]
Is weighted Rand Robin supported in Floodlight? How to use it?

**Comment by OCoutinho** [comment]
It is possible, follow the tutorial [in](https://floodlight.atlassian.net/wiki/spaces/floodlightcontroller/pages/1343617/Load+Balancer)

Then:
1) Add parameter { ..., "lbMethod": "WRR" } to the json request of the pool created.

2) Use this endpoint to set weights to the members of that : /quantum/v1.0/members/"member_id"/"weight_value"}.

Weights are integers from 1-10.

For other functionalities and full documentation, you can clone my fork of floodlight repository: https://github.com/OCoutinho/floodlight/tree/lbstats-monitors

With documentation: https://github.com/OCoutinho/floodlight/wiki/Load-Balancer-API 

Most of these functionalities are waiting approval in issue #753.

**Comment by omidit** [comment]
@OCoutinho : thanks for reply

**Pull request merged**
